---
title: "CodeBook"
author: "Noura Azeem"
date: "4/14/2020"
output: html_document
---


1. Merges the training and the test sets to create one data set.

Loading in the labels
features <- Reads in the feature labels
activityLabels <- Reads in the Activity labels

Loading in the test data
subject_test <- Subject test dataset
X_test <- x test dataset
y_test <- y test dataset

Loading in the train data
subject_train <- subject train dataset
X_train <- x training dataset
y_train <- y training datatset


XTrain <- Binding the X train and X test datasets
YTrain <- Binding the  y_train and y_test datasets
Subjects <- Binding the subject_trai and subject_test datasets
mergedData <- Binding the Subjects, YTrain, XTrain datasets

2. Extracts only the measurements on the mean and standard deviation for each measurement.
TidyData <- Using the mergedData dataset to extract only values that have mean and standard deviations

The number of variables goes down from 561 to 88 variables

3. Uses descriptive activity names to name the activities in the data set
TidyData$code <- Assigning the descriptive activity names to the dataset

4. Appropriately labels the data set with descriptive variable names.

leading t or f is based on time or frequency measurements.
Body = related to body movement.
Gravity = acceleration of gravity
Acc = accelerometer measurement
Gyro = gyroscopic measurements
Jerk = sudden movement acceleration
Mag = magnitude of movement
mean and SD are calculated for each subject for each activity for each mean and SD measurements. 
The units given are g’s for the accelerometer and rad/sec for the gyro and g/sec and rad/sec/sec for the corresponding jerks.

names(TidyData)[2] = "activity"
names(TidyData)<-gsub("^t", "Time", names(TidyData))
names(TidyData)<-gsub("^f", "Frequency", names(TidyData))

names(TidyData)<-gsub("tBody", "TimeBody", names(TidyData))
names(TidyData)<-gsub("BodyBody", "Body", names(TidyData))

names(TidyData)<-gsub("Acc", "Accelerometer", names(TidyData))
names(TidyData)<-gsub("Gyro", "Gyroscope", names(TidyData))
names(TidyData)<-gsub("Mag", "Magnitude", names(TidyData))
names(TidyData)<-gsub("-mean()", "Mean", names(TidyData), ignore.case = TRUE)
names(TidyData)<-gsub("-std()", "STD", names(TidyData), ignore.case = TRUE)
names(TidyData)<-gsub("-freq()", "Frequency", names(TidyData), ignore.case = TRUE)
names(TidyData)<-gsub("angle", "Angle", names(TidyData))
names(TidyData)<-gsub("gravity", "Gravity", names(TidyData))


5. From the data set in step 4, creates a second, independent tidy data set with the 
average of each variable for each activity and each subject.


Finale<- Final dataset that creates a tidy dataset with the average of each variable for each activity and subject
write.table(Finale, "Finale.txt", row.name=FALSE) <- this function creates the txt file for us















2. Extracts only the measurements on the mean and standard deviation for each measurement.
3. Uses descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive variable names.
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.